// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/v1/chef.proto

package vchefv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRecipeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ingredients     []string               `protobuf:"bytes,1,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	MealType        string                 `protobuf:"bytes,2,opt,name=meal_type,json=mealType,proto3" json:"meal_type,omitempty"`
	DietaryCategory string                 `protobuf:"bytes,3,opt,name=dietary_category,json=dietaryCategory,proto3" json:"dietary_category,omitempty"`
	MaxPrepTimeMins int32                  `protobuf:"varint,4,opt,name=max_prep_time_mins,json=maxPrepTimeMins,proto3" json:"max_prep_time_mins,omitempty"`
	TargetCalories  int32                  `protobuf:"varint,5,opt,name=target_calories,json=targetCalories,proto3" json:"target_calories,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateRecipeRequest) Reset() {
	*x = GenerateRecipeRequest{}
	mi := &file_proto_v1_chef_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRecipeRequest) ProtoMessage() {}

func (x *GenerateRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_chef_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRecipeRequest.ProtoReflect.Descriptor instead.
func (*GenerateRecipeRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_chef_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRecipeRequest) GetIngredients() []string {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *GenerateRecipeRequest) GetMealType() string {
	if x != nil {
		return x.MealType
	}
	return ""
}

func (x *GenerateRecipeRequest) GetDietaryCategory() string {
	if x != nil {
		return x.DietaryCategory
	}
	return ""
}

func (x *GenerateRecipeRequest) GetMaxPrepTimeMins() int32 {
	if x != nil {
		return x.MaxPrepTimeMins
	}
	return 0
}

func (x *GenerateRecipeRequest) GetTargetCalories() int32 {
	if x != nil {
		return x.TargetCalories
	}
	return 0
}

type RecipeIngredient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	InFridge      bool                   `protobuf:"varint,4,opt,name=in_fridge,json=inFridge,proto3" json:"in_fridge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeIngredient) Reset() {
	*x = RecipeIngredient{}
	mi := &file_proto_v1_chef_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeIngredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeIngredient) ProtoMessage() {}

func (x *RecipeIngredient) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_chef_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeIngredient.ProtoReflect.Descriptor instead.
func (*RecipeIngredient) Descriptor() ([]byte, []int) {
	return file_proto_v1_chef_proto_rawDescGZIP(), []int{1}
}

func (x *RecipeIngredient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecipeIngredient) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RecipeIngredient) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *RecipeIngredient) GetInFridge() bool {
	if x != nil {
		return x.InFridge
	}
	return false
}

type GenerateRecipeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PrepTimeMins  int32                  `protobuf:"varint,3,opt,name=prep_time_mins,json=prepTimeMins,proto3" json:"prep_time_mins,omitempty"`
	CookTimeMins  int32                  `protobuf:"varint,4,opt,name=cook_time_mins,json=cookTimeMins,proto3" json:"cook_time_mins,omitempty"`
	Servings      int32                  `protobuf:"varint,5,opt,name=servings,proto3" json:"servings,omitempty"`
	Calories      int32                  `protobuf:"varint,6,opt,name=calories,proto3" json:"calories,omitempty"`
	ProteinGrams  float64                `protobuf:"fixed64,7,opt,name=protein_grams,json=proteinGrams,proto3" json:"protein_grams,omitempty"`
	FatGrams      float64                `protobuf:"fixed64,8,opt,name=fat_grams,json=fatGrams,proto3" json:"fat_grams,omitempty"`
	CarbsGrams    float64                `protobuf:"fixed64,9,opt,name=carbs_grams,json=carbsGrams,proto3" json:"carbs_grams,omitempty"`
	Ingredients   []*RecipeIngredient    `protobuf:"bytes,10,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	Steps         []string               `protobuf:"bytes,11,rep,name=steps,proto3" json:"steps,omitempty"`
	GeneratedAt   string                 `protobuf:"bytes,12,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRecipeResponse) Reset() {
	*x = GenerateRecipeResponse{}
	mi := &file_proto_v1_chef_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRecipeResponse) ProtoMessage() {}

func (x *GenerateRecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_chef_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRecipeResponse.ProtoReflect.Descriptor instead.
func (*GenerateRecipeResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_chef_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateRecipeResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GenerateRecipeResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GenerateRecipeResponse) GetPrepTimeMins() int32 {
	if x != nil {
		return x.PrepTimeMins
	}
	return 0
}

func (x *GenerateRecipeResponse) GetCookTimeMins() int32 {
	if x != nil {
		return x.CookTimeMins
	}
	return 0
}

func (x *GenerateRecipeResponse) GetServings() int32 {
	if x != nil {
		return x.Servings
	}
	return 0
}

func (x *GenerateRecipeResponse) GetCalories() int32 {
	if x != nil {
		return x.Calories
	}
	return 0
}

func (x *GenerateRecipeResponse) GetProteinGrams() float64 {
	if x != nil {
		return x.ProteinGrams
	}
	return 0
}

func (x *GenerateRecipeResponse) GetFatGrams() float64 {
	if x != nil {
		return x.FatGrams
	}
	return 0
}

func (x *GenerateRecipeResponse) GetCarbsGrams() float64 {
	if x != nil {
		return x.CarbsGrams
	}
	return 0
}

func (x *GenerateRecipeResponse) GetIngredients() []*RecipeIngredient {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *GenerateRecipeResponse) GetSteps() []string {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *GenerateRecipeResponse) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_v1_chef_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_chef_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_chef_proto_rawDescGZIP(), []int{3}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_v1_chef_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_chef_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_chef_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_v1_chef_proto protoreflect.FileDescriptor

const file_proto_v1_chef_proto_rawDesc = "" +
	"\n" +
	"\x13proto/v1/chef.proto\x12\bvchef.v1\"\xd7\x01\n" +
	"\x15GenerateRecipeRequest\x12 \n" +
	"\vingredients\x18\x01 \x03(\tR\vingredients\x12\x1b\n" +
	"\tmeal_type\x18\x02 \x01(\tR\bmealType\x12)\n" +
	"\x10dietary_category\x18\x03 \x01(\tR\x0fdietaryCategory\x12+\n" +
	"\x12max_prep_time_mins\x18\x04 \x01(\x05R\x0fmaxPrepTimeMins\x12'\n" +
	"\x0ftarget_calories\x18\x05 \x01(\x05R\x0etargetCalories\"s\n" +
	"\x10RecipeIngredient\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x1b\n" +
	"\tin_fridge\x18\x04 \x01(\bR\binFridge\"\xae\x03\n" +
	"\x16GenerateRecipeResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12$\n" +
	"\x0eprep_time_mins\x18\x03 \x01(\x05R\fprepTimeMins\x12$\n" +
	"\x0ecook_time_mins\x18\x04 \x01(\x05R\fcookTimeMins\x12\x1a\n" +
	"\bservings\x18\x05 \x01(\x05R\bservings\x12\x1a\n" +
	"\bcalories\x18\x06 \x01(\x05R\bcalories\x12#\n" +
	"\rprotein_grams\x18\a \x01(\x01R\fproteinGrams\x12\x1b\n" +
	"\tfat_grams\x18\b \x01(\x01R\bfatGrams\x12\x1f\n" +
	"\vcarbs_grams\x18\t \x01(\x01R\n" +
	"carbsGrams\x12<\n" +
	"\vingredients\x18\n" +
	" \x03(\v2\x1a.vchef.v1.RecipeIngredientR\vingredients\x12\x14\n" +
	"\x05steps\x18\v \x03(\tR\x05steps\x12!\n" +
	"\fgenerated_at\x18\f \x01(\tR\vgeneratedAt\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xae\x01\n" +
	"\vChefService\x12S\n" +
	"\x0eGenerateRecipe\x12\x1f.vchef.v1.GenerateRecipeRequest\x1a .vchef.v1.GenerateRecipeResponse\x12J\n" +
	"\vHealthCheck\x12\x1c.vchef.v1.HealthCheckRequest\x1a\x1d.vchef.v1.HealthCheckResponseB0Z.github.com/ynshvrh/V-Chef/pkg/vchef/v1;vchefv1b\x06proto3"

var (
	file_proto_v1_chef_proto_rawDescOnce sync.Once
	file_proto_v1_chef_proto_rawDescData []byte
)

func file_proto_v1_chef_proto_rawDescGZIP() []byte {
	file_proto_v1_chef_proto_rawDescOnce.Do(func() {
		file_proto_v1_chef_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_chef_proto_rawDesc), len(file_proto_v1_chef_proto_rawDesc)))
	})
	return file_proto_v1_chef_proto_rawDescData
}

var file_proto_v1_chef_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_v1_chef_proto_goTypes = []any{
	(*GenerateRecipeRequest)(nil),  // 0: vchef.v1.GenerateRecipeRequest
	(*RecipeIngredient)(nil),       // 1: vchef.v1.RecipeIngredient
	(*GenerateRecipeResponse)(nil), // 2: vchef.v1.GenerateRecipeResponse
	(*HealthCheckRequest)(nil),     // 3: vchef.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 4: vchef.v1.HealthCheckResponse
}
var file_proto_v1_chef_proto_depIdxs = []int32{
	1, // 0: vchef.v1.GenerateRecipeResponse.ingredients:type_name -> vchef.v1.RecipeIngredient
	0, // 1: vchef.v1.ChefService.GenerateRecipe:input_type -> vchef.v1.GenerateRecipeRequest
	3, // 2: vchef.v1.ChefService.HealthCheck:input_type -> vchef.v1.HealthCheckRequest
	2, // 3: vchef.v1.ChefService.GenerateRecipe:output_type -> vchef.v1.GenerateRecipeResponse
	4, // 4: vchef.v1.ChefService.HealthCheck:output_type -> vchef.v1.HealthCheckResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_v1_chef_proto_init() }
func file_proto_v1_chef_proto_init() {
	if File_proto_v1_chef_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_chef_proto_rawDesc), len(file_proto_v1_chef_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_chef_proto_goTypes,
		DependencyIndexes: file_proto_v1_chef_proto_depIdxs,
		MessageInfos:      file_proto_v1_chef_proto_msgTypes,
	}.Build()
	File_proto_v1_chef_proto = out.File
	file_proto_v1_chef_proto_goTypes = nil
	file_proto_v1_chef_proto_depIdxs = nil
}
