// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/v1/chef.proto

package vchefv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChefService_GenerateRecipe_FullMethodName = "/vchef.v1.ChefService/GenerateRecipe"
	ChefService_HealthCheck_FullMethodName    = "/vchef.v1.ChefService/HealthCheck"
)

// ChefServiceClient is the client API for ChefService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChefServiceClient interface {
	GenerateRecipe(ctx context.Context, in *GenerateRecipeRequest, opts ...grpc.CallOption) (*GenerateRecipeResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type chefServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChefServiceClient(cc grpc.ClientConnInterface) ChefServiceClient {
	return &chefServiceClient{cc}
}

func (c *chefServiceClient) GenerateRecipe(ctx context.Context, in *GenerateRecipeRequest, opts ...grpc.CallOption) (*GenerateRecipeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateRecipeResponse)
	err := c.cc.Invoke(ctx, ChefService_GenerateRecipe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chefServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ChefService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChefServiceServer is the server API for ChefService service.
// All implementations must embed UnimplementedChefServiceServer
// for forward compatibility.
type ChefServiceServer interface {
	GenerateRecipe(context.Context, *GenerateRecipeRequest) (*GenerateRecipeResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedChefServiceServer()
}

// UnimplementedChefServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChefServiceServer struct{}

func (UnimplementedChefServiceServer) GenerateRecipe(context.Context, *GenerateRecipeRequest) (*GenerateRecipeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateRecipe not implemented")
}
func (UnimplementedChefServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedChefServiceServer) mustEmbedUnimplementedChefServiceServer() {}
func (UnimplementedChefServiceServer) testEmbeddedByValue()                     {}

// UnsafeChefServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChefServiceServer will
// result in compilation errors.
type UnsafeChefServiceServer interface {
	mustEmbedUnimplementedChefServiceServer()
}

func RegisterChefServiceServer(s grpc.ServiceRegistrar, srv ChefServiceServer) {
	// If the following call panics, it indicates UnimplementedChefServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChefService_ServiceDesc, srv)
}

func _ChefService_GenerateRecipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRecipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChefServiceServer).GenerateRecipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChefService_GenerateRecipe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChefServiceServer).GenerateRecipe(ctx, req.(*GenerateRecipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChefService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChefServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChefService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChefServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChefService_ServiceDesc is the grpc.ServiceDesc for ChefService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChefService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vchef.v1.ChefService",
	HandlerType: (*ChefServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateRecipe",
			Handler:    _ChefService_GenerateRecipe_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ChefService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/chef.proto",
}
